Added before script
woolfg/mysql-backup-sidecar pull request #14
Opened 2022-01-15 20:23 UTC by lightningspirit

This PR adds a env var to configure a before run script.
It's useful in the situation you want to measure performance or send events to an event stream like Kafka.

2022-01-18 15:22 UTC, woolfg requested changes
thanks a lot for the PR, looks good. could you just add the requested information to the readme, then I'll merge it. thanks for the contribution :green_heart:

2022-01-18 15:22 UTC, woolfg commented on README.md
> +- `BEFORE_BACKUP_SCRIPT:` "/backup/before_script.sh"
could you please add the information about the first parameter that you hand over to the before script.

2022-01-19 17:02 UTC, lightningspirit commented on README.md
> +- `BEFORE_BACKUP_SCRIPT:` "/backup/before_script.sh"
Sure thing, no problem, I can do it 😉

2022-01-23 00:20 UTC, lightningspirit commented
Hi @woolfg 👋 I just added a section in README about the after and before scripts. Is this ok for you?

2022-01-25 13:51 UTC, woolfg commented
thanks for the contribution, looks good

2022-01-25 13:51 UTC, merged